export const PLAYER = {
  BLACK: 'BLACK',
  WHITE: 'WHITE',
}

export const PIECE = {
  PAWN: 'PAWN',
  KNIGHT: 'KNIGHT',
  BISHOP: 'BISHOP',
  ROOK: 'ROOK',
  QUEEN: 'QUEEN',
  KING: 'KING',
}


export const GAME_STATE = {
  IN_PROGRESS: 'IN_PROGRESS',
  CHECKMATE: 'CHECKMATE',
  STALEMATE: 'STALEMATE',
}